// Word bank. Each entry: the secret WORD (everyone sees it) + a related HINT
// shown only to the imposter. The raw hints stay close to the word for easy
// maintenance; HARD_HINTS below replaces them with broader clues in-game.
// Languages: en = English, mn = Mongolian (Cyrillic), kk = Kazakh (Cyrillic).
const RAW = [
  // ── Animals ──────────────────────────────────────────────
  { word: { en: 'Lion', mn: 'Арслан', kk: 'Арыстан' }, hint: { en: 'Africa', mn: 'Африк', kk: 'Африка' } },
  { word: { en: 'Tiger', mn: 'Бар', kk: 'Жолбарыс' }, hint: { en: 'Stripes', mn: 'Судал', kk: 'Жолақ' } },
  { word: { en: 'Elephant', mn: 'Заан', kk: 'Піл' }, hint: { en: 'Tusk', mn: 'Соёо', kk: 'Азу' } },
  { word: { en: 'Giraffe', mn: 'Анааш', kk: 'Жираф' }, hint: { en: 'Neck', mn: 'Хүзүү', kk: 'Мойын' } },
  { word: { en: 'Zebra', mn: 'Тахь илжиг', kk: 'Зебра' }, hint: { en: 'Stripes', mn: 'Судал', kk: 'Жолақ' } },
  { word: { en: 'Monkey', mn: 'Сармагчин', kk: 'Маймыл' }, hint: { en: 'Banana', mn: 'Гадил', kk: 'Банан' } },
  { word: { en: 'Bear', mn: 'Баавгай', kk: 'Аю' }, hint: { en: 'Forest', mn: 'Ой', kk: 'Орман' } },
  { word: { en: 'Wolf', mn: 'Чоно', kk: 'Қасқыр' }, hint: { en: 'Pack', mn: 'Сүрэг', kk: 'Тобыр' } },
  { word: { en: 'Fox', mn: 'Үнэг', kk: 'Түлкі' }, hint: { en: 'Cunning', mn: 'Зальтай', kk: 'Айлакер' } },
  { word: { en: 'Rabbit', mn: 'Туулай', kk: 'Қоян' }, hint: { en: 'Carrot', mn: 'Лууван', kk: 'Сәбіз' } },
  { word: { en: 'Deer', mn: 'Буга', kk: 'Бұғы' }, hint: { en: 'Antler', mn: 'Эвэр', kk: 'Мүйіз' } },
  { word: { en: 'Horse', mn: 'Морь', kk: 'Жылқы' }, hint: { en: 'Steppe', mn: 'Тал нутаг', kk: 'Дала' } },
  { word: { en: 'Camel', mn: 'Тэмээ', kk: 'Түйе' }, hint: { en: 'Desert', mn: 'Цөл', kk: 'Шөл' } },
  { word: { en: 'Cow', mn: 'Үнээ', kk: 'Сиыр' }, hint: { en: 'Milk', mn: 'Сүү', kk: 'Сүт' } },
  { word: { en: 'Sheep', mn: 'Хонь', kk: 'Қой' }, hint: { en: 'Wool', mn: 'Ноос', kk: 'Жүн' } },
  { word: { en: 'Goat', mn: 'Ямаа', kk: 'Ешкі' }, hint: { en: 'Mountain', mn: 'Уул', kk: 'Тау' } },
  { word: { en: 'Pig', mn: 'Гахай', kk: 'Шошқа' }, hint: { en: 'Mud', mn: 'Шавар', kk: 'Балшық' } },
  { word: { en: 'Chicken', mn: 'Тахиа', kk: 'Тауық' }, hint: { en: 'Egg', mn: 'Өндөг', kk: 'Жұмыртқа' } },
  { word: { en: 'Duck', mn: 'Нугас', kk: 'Үйрек' }, hint: { en: 'Pond', mn: 'Цөөрөм', kk: 'Тоған' } },
  { word: { en: 'Eagle', mn: 'Бүргэд', kk: 'Бүркіт' }, hint: { en: 'Sky', mn: 'Тэнгэр', kk: 'Аспан' } },
  { word: { en: 'Owl', mn: 'Шар шувуу', kk: 'Үкі' }, hint: { en: 'Night', mn: 'Шөнө', kk: 'Түн' } },
  { word: { en: 'Penguin', mn: 'Оцон шувуу', kk: 'Пингвин' }, hint: { en: 'Antarctica', mn: 'Антарктид', kk: 'Антарктида' } },
  { word: { en: 'Parrot', mn: 'Тоть', kk: 'Тотықұс' }, hint: { en: 'Colorful', mn: 'Өнгөлөг', kk: 'Түрлі-түсті' } },
  { word: { en: 'Peacock', mn: 'Тогос', kk: 'Тауыс' }, hint: { en: 'Feather', mn: 'Өд', kk: 'Қауырсын' } },
  { word: { en: 'Snake', mn: 'Могой', kk: 'Жылан' }, hint: { en: 'Venom', mn: 'Хор', kk: 'У' } },
  { word: { en: 'Crocodile', mn: 'Матар', kk: 'Қолтырауын' }, hint: { en: 'River', mn: 'Гол', kk: 'Өзен' } },
  { word: { en: 'Turtle', mn: 'Яст мэлхий', kk: 'Тасбақа' }, hint: { en: 'Shell', mn: 'Хясаа', kk: 'Қабыршақ' } },
  { word: { en: 'Frog', mn: 'Мэлхий', kk: 'Бақа' }, hint: { en: 'Jump', mn: 'Үсрэх', kk: 'Секіру' } },
  { word: { en: 'Fish', mn: 'Загас', kk: 'Балық' }, hint: { en: 'Water', mn: 'Ус', kk: 'Су' } },
  { word: { en: 'Shark', mn: 'Акул', kk: 'Акула' }, hint: { en: 'Ocean', mn: 'Далай', kk: 'Мұхит' } },
  { word: { en: 'Whale', mn: 'Халим', kk: 'Кит' }, hint: { en: 'Giant', mn: 'Аварга', kk: 'Алып' } },
  { word: { en: 'Dolphin', mn: 'Далайн гахай', kk: 'Дельфин' }, hint: { en: 'Smart', mn: 'Ухаантай', kk: 'Ақылды' } },
  { word: { en: 'Octopus', mn: 'Наймаалж', kk: 'Сегізаяқ' }, hint: { en: 'Tentacle', mn: 'Хөл', kk: 'Шатыс' } },
  { word: { en: 'Bee', mn: 'Зөгий', kk: 'Ара' }, hint: { en: 'Honey', mn: 'Бал', kk: 'Бал' } },
  { word: { en: 'Butterfly', mn: 'Эрвээхэй', kk: 'Көбелек' }, hint: { en: 'Flower', mn: 'Цэцэг', kk: 'Гүл' } },
  { word: { en: 'Spider', mn: 'Аалз', kk: 'Өрмекші' }, hint: { en: 'Web', mn: 'Тор', kk: 'Тор' } },
  { word: { en: 'Ant', mn: 'Шоргоолж', kk: 'Құмырсқа' }, hint: { en: 'Colony', mn: 'Үүр', kk: 'Илеу' } },
  { word: { en: 'Kangaroo', mn: 'Кенгуру', kk: 'Кенгуру' }, hint: { en: 'Australia', mn: 'Австрали', kk: 'Австралия' } },
  { word: { en: 'Panda', mn: 'Панда', kk: 'Панда' }, hint: { en: 'Bamboo', mn: 'Хулс', kk: 'Бамбук' } },
  { word: { en: 'Squirrel', mn: 'Хэрэм', kk: 'Тиін' }, hint: { en: 'Nut', mn: 'Самар', kk: 'Жаңғақ' } },
  { word: { en: 'Bat', mn: 'Сарьсан багваахай', kk: 'Жарқанат' }, hint: { en: 'Cave', mn: 'Агуй', kk: 'Үңгір' } },
  { word: { en: 'Dog', mn: 'Нохой', kk: 'Ит' }, hint: { en: 'Loyal', mn: 'Үнэнч', kk: 'Адал' } },
  { word: { en: 'Cat', mn: 'Муур', kk: 'Мысық' }, hint: { en: 'Whiskers', mn: 'Сахал', kk: 'Мұрт' } },
  { word: { en: 'Mouse', mn: 'Хулгана', kk: 'Тышқан' }, hint: { en: 'Cheese', mn: 'Бяслаг', kk: 'Ірімшік' } },
  { word: { en: 'Rhino', mn: 'Хирс', kk: 'Мүйізтұмсық' }, hint: { en: 'Horn', mn: 'Эвэр', kk: 'Мүйіз' } },
  { word: { en: 'Hippo', mn: 'Усны морь', kk: 'Бегемот' }, hint: { en: 'River', mn: 'Гол', kk: 'Өзен' } },

  // ── Food & drink ─────────────────────────────────────────
  { word: { en: 'Pizza', mn: 'Пицца', kk: 'Пицца' }, hint: { en: 'Italy', mn: 'Итали', kk: 'Италия' } },
  { word: { en: 'Sushi', mn: 'Суши', kk: 'Суши' }, hint: { en: 'Japan', mn: 'Япон', kk: 'Жапония' } },
  { word: { en: 'Burger', mn: 'Бургер', kk: 'Бургер' }, hint: { en: 'Fast food', mn: 'Түргэн хоол', kk: 'Фастфуд' } },
  { word: { en: 'Pasta', mn: 'Макарон', kk: 'Макарон' }, hint: { en: 'Italy', mn: 'Итали', kk: 'Италия' } },
  { word: { en: 'Dumpling', mn: 'Бууз', kk: 'Манты' }, hint: { en: 'Steam', mn: 'Уур', kk: 'Бу' } },
  { word: { en: 'Soup', mn: 'Шөл', kk: 'Сорпа' }, hint: { en: 'Hot', mn: 'Халуун', kk: 'Ыстық' } },
  { word: { en: 'Bread', mn: 'Талх', kk: 'Нан' }, hint: { en: 'Flour', mn: 'Гурил', kk: 'Ұн' } },
  { word: { en: 'Rice', mn: 'Будаа', kk: 'Күріш' }, hint: { en: 'Asia', mn: 'Ази', kk: 'Азия' } },
  { word: { en: 'Cheese', mn: 'Бяслаг', kk: 'Ірімшік' }, hint: { en: 'Milk', mn: 'Сүү', kk: 'Сүт' } },
  { word: { en: 'Egg', mn: 'Өндөг', kk: 'Жұмыртқа' }, hint: { en: 'Breakfast', mn: 'Өглөөний цай', kk: 'Таңғы ас' } },
  { word: { en: 'Chocolate', mn: 'Шоколад', kk: 'Шоколад' }, hint: { en: 'Sweet', mn: 'Чихэрлэг', kk: 'Тәтті' } },
  { word: { en: 'Ice cream', mn: 'Зайрмаг', kk: 'Балмұздақ' }, hint: { en: 'Cold', mn: 'Хүйтэн', kk: 'Суық' } },
  { word: { en: 'Cake', mn: 'Бялуу', kk: 'Торт' }, hint: { en: 'Birthday', mn: 'Төрсөн өдөр', kk: 'Туған күн' } },
  { word: { en: 'Honey', mn: 'Бал', kk: 'Бал' }, hint: { en: 'Bee', mn: 'Зөгий', kk: 'Ара' } },
  { word: { en: 'Salt', mn: 'Давс', kk: 'Тұз' }, hint: { en: 'Sea', mn: 'Тэнгис', kk: 'Теңіз' } },
  { word: { en: 'Sugar', mn: 'Чихэр', kk: 'Қант' }, hint: { en: 'Sweet', mn: 'Амтлаг', kk: 'Тәтті' } },
  { word: { en: 'Coffee', mn: 'Кофе', kk: 'Кофе' }, hint: { en: 'Morning', mn: 'Өглөө', kk: 'Таң' } },
  { word: { en: 'Tea', mn: 'Цай', kk: 'Шай' }, hint: { en: 'Hot drink', mn: 'Халуун ундаа', kk: 'Ыстық сусын' } },
  { word: { en: 'Milk', mn: 'Сүү', kk: 'Сүт' }, hint: { en: 'Cow', mn: 'Үнээ', kk: 'Сиыр' } },
  { word: { en: 'Wine', mn: 'Дарс', kk: 'Шарап' }, hint: { en: 'Grape', mn: 'Усан үзэм', kk: 'Жүзім' } },
  { word: { en: 'Apple', mn: 'Алим', kk: 'Алма' }, hint: { en: 'Fruit', mn: 'Жимс', kk: 'Жеміс' } },
  { word: { en: 'Banana', mn: 'Гадил', kk: 'Банан' }, hint: { en: 'Yellow', mn: 'Шар', kk: 'Сары' } },
  { word: { en: 'Orange', mn: 'Жүрж', kk: 'Апельсин' }, hint: { en: 'Vitamin', mn: 'Витамин', kk: 'Витамин' } },
  { word: { en: 'Grape', mn: 'Усан үзэм', kk: 'Жүзім' }, hint: { en: 'Wine', mn: 'Дарс', kk: 'Шарап' } },
  { word: { en: 'Watermelon', mn: 'Тарвас', kk: 'Қарбыз' }, hint: { en: 'Summer', mn: 'Зун', kk: 'Жаз' } },
  { word: { en: 'Lemon', mn: 'Нимбэг', kk: 'Лимон' }, hint: { en: 'Sour', mn: 'Исгэлэн', kk: 'Қышқыл' } },
  { word: { en: 'Strawberry', mn: 'Гүзээлзгэнэ', kk: 'Құлпынай' }, hint: { en: 'Red', mn: 'Улаан', kk: 'Қызыл' } },
  { word: { en: 'Potato', mn: 'Төмс', kk: 'Картоп' }, hint: { en: 'Fries', mn: 'Шарсан', kk: 'Фри' } },
  { word: { en: 'Tomato', mn: 'Улаан лооль', kk: 'Қызанақ' }, hint: { en: 'Sauce', mn: 'Соус', kk: 'Тұздық' } },
  { word: { en: 'Onion', mn: 'Сонгино', kk: 'Пияз' }, hint: { en: 'Tears', mn: 'Нулимс', kk: 'Көзжас' } },
  { word: { en: 'Carrot', mn: 'Лууван', kk: 'Сәбіз' }, hint: { en: 'Rabbit', mn: 'Туулай', kk: 'Қоян' } },
  { word: { en: 'Garlic', mn: 'Сармис', kk: 'Сарымсақ' }, hint: { en: 'Smell', mn: 'Үнэр', kk: 'Иіс' } },
  { word: { en: 'Noodle', mn: 'Гоймон', kk: 'Кеспе' }, hint: { en: 'Soup', mn: 'Шөл', kk: 'Сорпа' } },
  { word: { en: 'Popcorn', mn: 'Попкорн', kk: 'Попкорн' }, hint: { en: 'Cinema', mn: 'Кино театр', kk: 'Кинотеатр' } },
  { word: { en: 'Pancake', mn: 'Хуушуур', kk: 'Құймақ' }, hint: { en: 'Pan', mn: 'Хайруул', kk: 'Таба' } },

  // ── Places & landmarks ───────────────────────────────────
  { word: { en: 'Beach', mn: 'Далайн эрэг', kk: 'Жағажай' }, hint: { en: 'Summer', mn: 'Зун', kk: 'Жаз' } },
  { word: { en: 'Desert', mn: 'Цөл', kk: 'Шөл' }, hint: { en: 'Sand', mn: 'Элс', kk: 'Құм' } },
  { word: { en: 'Forest', mn: 'Ой', kk: 'Орман' }, hint: { en: 'Tree', mn: 'Мод', kk: 'Ағаш' } },
  { word: { en: 'Mountain', mn: 'Уул', kk: 'Тау' }, hint: { en: 'High', mn: 'Өндөр', kk: 'Биік' } },
  { word: { en: 'River', mn: 'Гол', kk: 'Өзен' }, hint: { en: 'Flow', mn: 'Урсгал', kk: 'Ағын' } },
  { word: { en: 'Island', mn: 'Арал', kk: 'Арал' }, hint: { en: 'Ocean', mn: 'Далай', kk: 'Мұхит' } },
  { word: { en: 'Volcano', mn: 'Галт уул', kk: 'Жанартау' }, hint: { en: 'Lava', mn: 'Лаав', kk: 'Лава' } },
  { word: { en: 'Cave', mn: 'Агуй', kk: 'Үңгір' }, hint: { en: 'Dark', mn: 'Харанхуй', kk: 'Қараңғы' } },
  { word: { en: 'Waterfall', mn: 'Хүрхрээ', kk: 'Сарқырама' }, hint: { en: 'Fall', mn: 'Унах', kk: 'Құлау' } },
  { word: { en: 'Bridge', mn: 'Гүүр', kk: 'Көпір' }, hint: { en: 'River', mn: 'Гол', kk: 'Өзен' } },
  { word: { en: 'Castle', mn: 'Шилтгээн', kk: 'Қамал' }, hint: { en: 'King', mn: 'Хаан', kk: 'Патша' } },
  { word: { en: 'Pyramid', mn: 'Пирамид', kk: 'Пирамида' }, hint: { en: 'Egypt', mn: 'Египет', kk: 'Мысыр' } },
  { word: { en: 'Tower', mn: 'Цамхаг', kk: 'Мұнара' }, hint: { en: 'Tall', mn: 'Өндөр', kk: 'Биік' } },
  { word: { en: 'Lighthouse', mn: 'Гэрэлт цамхаг', kk: 'Шамшырақ' }, hint: { en: 'Coast', mn: 'Эрэг', kk: 'Жаға' } },
  { word: { en: 'Market', mn: 'Зах', kk: 'Базар' }, hint: { en: 'Buy', mn: 'Худалдаж авах', kk: 'Сатып алу' } },
  { word: { en: 'Library', mn: 'Номын сан', kk: 'Кітапхана' }, hint: { en: 'Quiet', mn: 'Чимээгүй', kk: 'Тыныш' } },
  { word: { en: 'Hospital', mn: 'Эмнэлэг', kk: 'Аурухана' }, hint: { en: 'Nurse', mn: 'Сувилагч', kk: 'Мейірбике' } },
  { word: { en: 'School', mn: 'Сургууль', kk: 'Мектеп' }, hint: { en: 'Pupil', mn: 'Сурагч', kk: 'Оқушы' } },
  { word: { en: 'Airport', mn: 'Нисэх буудал', kk: 'Әуежай' }, hint: { en: 'Flight', mn: 'Нислэг', kk: 'Ұшу' } },
  { word: { en: 'Zoo', mn: 'Амьтны хүрээлэн', kk: 'Хайуанаттар бағы' }, hint: { en: 'Cage', mn: 'Тор', kk: 'Тор' } },
  { word: { en: 'Stadium', mn: 'Цэнгэлдэх', kk: 'Стадион' }, hint: { en: 'Crowd', mn: 'Олон түмэн', kk: 'Көпшілік' } },
  { word: { en: 'Museum', mn: 'Музей', kk: 'Мұражай' }, hint: { en: 'History', mn: 'Түүх', kk: 'Тарих' } },
  { word: { en: 'Restaurant', mn: 'Ресторан', kk: 'Мейрамхана' }, hint: { en: 'Menu', mn: 'Цэс', kk: 'Мәзір' } },
  { word: { en: 'Bank', mn: 'Банк', kk: 'Банк' }, hint: { en: 'Money', mn: 'Мөнгө', kk: 'Ақша' } },
  { word: { en: 'Farm', mn: 'Ферм', kk: 'Ферма' }, hint: { en: 'Animals', mn: 'Мал', kk: 'Мал' } },
  { word: { en: 'Prison', mn: 'Шорон', kk: 'Түрме' }, hint: { en: 'Bars', mn: 'Тор', kk: 'Тор' } },
  { word: { en: 'Church', mn: 'Сүм', kk: 'Шіркеу' }, hint: { en: 'Pray', mn: 'Залбирах', kk: 'Дұға' } },
  { word: { en: 'Garden', mn: 'Цэцэрлэг', kk: 'Бақ' }, hint: { en: 'Flowers', mn: 'Цэцэг', kk: 'Гүл' } },

  // ── Jobs ─────────────────────────────────────────────────
  { word: { en: 'Doctor', mn: 'Эмч', kk: 'Дәрігер' }, hint: { en: 'Hospital', mn: 'Эмнэлэг', kk: 'Аурухана' } },
  { word: { en: 'Teacher', mn: 'Багш', kk: 'Мұғалім' }, hint: { en: 'School', mn: 'Сургууль', kk: 'Мектеп' } },
  { word: { en: 'Police', mn: 'Цагдаа', kk: 'Полиция' }, hint: { en: 'Crime', mn: 'Гэмт хэрэг', kk: 'Қылмыс' } },
  { word: { en: 'Firefighter', mn: 'Гал сөнөөгч', kk: 'Өрт сөндіруші' }, hint: { en: 'Fire', mn: 'Гал', kk: 'Өрт' } },
  { word: { en: 'Pilot', mn: 'Нисгэгч', kk: 'Ұшқыш' }, hint: { en: 'Plane', mn: 'Онгоц', kk: 'Ұшақ' } },
  { word: { en: 'Chef', mn: 'Тогооч', kk: 'Аспаз' }, hint: { en: 'Kitchen', mn: 'Гал тогоо', kk: 'Ас үй' } },
  { word: { en: 'Farmer', mn: 'Тариаланч', kk: 'Диқан' }, hint: { en: 'Field', mn: 'Тариалан', kk: 'Егін' } },
  { word: { en: 'Soldier', mn: 'Цэрэг', kk: 'Сарбаз' }, hint: { en: 'War', mn: 'Дайн', kk: 'Соғыс' } },
  { word: { en: 'Singer', mn: 'Дуучин', kk: 'Әнші' }, hint: { en: 'Song', mn: 'Дуу', kk: 'Ән' } },
  { word: { en: 'Painter', mn: 'Зураач', kk: 'Суретші' }, hint: { en: 'Brush', mn: 'Бийр', kk: 'Қылқалам' } },
  { word: { en: 'Writer', mn: 'Зохиолч', kk: 'Жазушы' }, hint: { en: 'Book', mn: 'Ном', kk: 'Кітап' } },
  { word: { en: 'Judge', mn: 'Шүүгч', kk: 'Судья' }, hint: { en: 'Court', mn: 'Шүүх', kk: 'Сот' } },
  { word: { en: 'Dentist', mn: 'Шүдний эмч', kk: 'Тіс дәрігері' }, hint: { en: 'Teeth', mn: 'Шүд', kk: 'Тіс' } },
  { word: { en: 'Nurse', mn: 'Сувилагч', kk: 'Мейірбике' }, hint: { en: 'Care', mn: 'Асрах', kk: 'Күтім' } },
  { word: { en: 'Driver', mn: 'Жолооч', kk: 'Жүргізуші' }, hint: { en: 'Wheel', mn: 'Жолоо', kk: 'Руль' } },
  { word: { en: 'Barber', mn: 'Үсчин', kk: 'Шаштараз' }, hint: { en: 'Hair', mn: 'Үс', kk: 'Шаш' } },
  { word: { en: 'Astronaut', mn: 'Сансрын нисэгч', kk: 'Ғарышкер' }, hint: { en: 'Space', mn: 'Сансар', kk: 'Ғарыш' } },
  { word: { en: 'Scientist', mn: 'Эрдэмтэн', kk: 'Ғалым' }, hint: { en: 'Lab', mn: 'Лаборатори', kk: 'Зертхана' } },
  { word: { en: 'Photographer', mn: 'Гэрэл зурагчин', kk: 'Фотограф' }, hint: { en: 'Camera', mn: 'Камер', kk: 'Камера' } },
  { word: { en: 'Fisherman', mn: 'Загасчин', kk: 'Балықшы' }, hint: { en: 'Net', mn: 'Тор', kk: 'Ау' } },
  { word: { en: 'Hunter', mn: 'Анчин', kk: 'Аңшы' }, hint: { en: 'Gun', mn: 'Буу', kk: 'Мылтық' } },
  { word: { en: 'Carpenter', mn: 'Мужаан', kk: 'Ағаш ұстасы' }, hint: { en: 'Wood', mn: 'Мод', kk: 'Ағаш' } },
  { word: { en: 'Actor', mn: 'Жүжигчин', kk: 'Актер' }, hint: { en: 'Stage', mn: 'Тайз', kk: 'Сахна' } },
  { word: { en: 'Magician', mn: 'Илбэчин', kk: 'Сиқыршы' }, hint: { en: 'Trick', mn: 'Заль', kk: 'Айла' } },

  // ── Sports & games ───────────────────────────────────────
  { word: { en: 'Football', mn: 'Хөлбөмбөг', kk: 'Футбол' }, hint: { en: 'Goal', mn: 'Гоол', kk: 'Гол' } },
  { word: { en: 'Basketball', mn: 'Сагсан бөмбөг', kk: 'Баскетбол' }, hint: { en: 'Hoop', mn: 'Сагс', kk: 'Себет' } },
  { word: { en: 'Tennis', mn: 'Теннис', kk: 'Теннис' }, hint: { en: 'Racket', mn: 'Ракет', kk: 'Ракетка' } },
  { word: { en: 'Boxing', mn: 'Бокс', kk: 'Бокс' }, hint: { en: 'Glove', mn: 'Бээлий', kk: 'Қолғап' } },
  { word: { en: 'Swimming', mn: 'Усанд сэлэлт', kk: 'Жүзу' }, hint: { en: 'Pool', mn: 'Усан сан', kk: 'Бассейн' } },
  { word: { en: 'Wrestling', mn: 'Бөх', kk: 'Күрес' }, hint: { en: 'Strength', mn: 'Хүч', kk: 'Күш' } },
  { word: { en: 'Archery', mn: 'Сурын харваа', kk: 'Садақ ату' }, hint: { en: 'Arrow', mn: 'Сум', kk: 'Жебе' } },
  { word: { en: 'Skiing', mn: 'Цана', kk: 'Шаңғы' }, hint: { en: 'Snow', mn: 'Цас', kk: 'Қар' } },
  { word: { en: 'Chess', mn: 'Шатар', kk: 'Шахмат' }, hint: { en: 'Strategy', mn: 'Тактик', kk: 'Стратегия' } },
  { word: { en: 'Cards', mn: 'Хөзөр', kk: 'Карта' }, hint: { en: 'Luck', mn: 'Аз', kk: 'Бақ' } },
  { word: { en: 'Golf', mn: 'Гольф', kk: 'Гольф' }, hint: { en: 'Hole', mn: 'Нүх', kk: 'Шұңқыр' } },
  { word: { en: 'Cycling', mn: 'Дугуй унах', kk: 'Велоспорт' }, hint: { en: 'Pedal', mn: 'Гишгүүр', kk: 'Педаль' } },
  { word: { en: 'Marathon', mn: 'Марафон', kk: 'Марафон' }, hint: { en: 'Run', mn: 'Гүйх', kk: 'Жүгіру' } },
  { word: { en: 'Volleyball', mn: 'Волейбол', kk: 'Волейбол' }, hint: { en: 'Net', mn: 'Тор', kk: 'Тор' } },
  { word: { en: 'Skating', mn: 'Тэшүүр', kk: 'Коньки' }, hint: { en: 'Ice', mn: 'Мөс', kk: 'Мұз' } },

  // ── Nature & weather ─────────────────────────────────────
  { word: { en: 'Sun', mn: 'Нар', kk: 'Күн' }, hint: { en: 'Summer', mn: 'Зун', kk: 'Жаз' } },
  { word: { en: 'Moon', mn: 'Сар', kk: 'Ай' }, hint: { en: 'Night', mn: 'Шөнө', kk: 'Түн' } },
  { word: { en: 'Star', mn: 'Од', kk: 'Жұлдыз' }, hint: { en: 'Sky', mn: 'Тэнгэр', kk: 'Аспан' } },
  { word: { en: 'Rain', mn: 'Бороо', kk: 'Жаңбыр' }, hint: { en: 'Cloud', mn: 'Үүл', kk: 'Бұлт' } },
  { word: { en: 'Snow', mn: 'Цас', kk: 'Қар' }, hint: { en: 'Winter', mn: 'Өвөл', kk: 'Қыс' } },
  { word: { en: 'Wind', mn: 'Салхи', kk: 'Жел' }, hint: { en: 'Blow', mn: 'Үлээх', kk: 'Соғу' } },
  { word: { en: 'Thunder', mn: 'Аянга', kk: 'Найзағай' }, hint: { en: 'Storm', mn: 'Шуурга', kk: 'Дауыл' } },
  { word: { en: 'Rainbow', mn: 'Солонго', kk: 'Кемпірқосақ' }, hint: { en: 'Colors', mn: 'Өнгө', kk: 'Түс' } },
  { word: { en: 'Fire', mn: 'Гал', kk: 'От' }, hint: { en: 'Hot', mn: 'Халуун', kk: 'Ыстық' } },
  { word: { en: 'Ice', mn: 'Мөс', kk: 'Мұз' }, hint: { en: 'Cold', mn: 'Хүйтэн', kk: 'Суық' } },
  { word: { en: 'Cloud', mn: 'Үүл', kk: 'Бұлт' }, hint: { en: 'Sky', mn: 'Тэнгэр', kk: 'Аспан' } },
  { word: { en: 'Fog', mn: 'Манан', kk: 'Тұман' }, hint: { en: 'Blur', mn: 'Бүрхэг', kk: 'Бұлыңғыр' } },
  { word: { en: 'Tree', mn: 'Мод', kk: 'Ағаш' }, hint: { en: 'Forest', mn: 'Ой', kk: 'Орман' } },
  { word: { en: 'Flower', mn: 'Цэцэг', kk: 'Гүл' }, hint: { en: 'Spring', mn: 'Хавар', kk: 'Көктем' } },
  { word: { en: 'Leaf', mn: 'Навч', kk: 'Жапырақ' }, hint: { en: 'Autumn', mn: 'Намар', kk: 'Күз' } },
  { word: { en: 'Grass', mn: 'Өвс', kk: 'Шөп' }, hint: { en: 'Green', mn: 'Ногоон', kk: 'Жасыл' } },
  { word: { en: 'Mushroom', mn: 'Мөөг', kk: 'Саңырауқұлақ' }, hint: { en: 'Forest', mn: 'Ой', kk: 'Орман' } },
  { word: { en: 'Cactus', mn: 'Кактус', kk: 'Кактус' }, hint: { en: 'Desert', mn: 'Цөл', kk: 'Шөл' } },
  { word: { en: 'Ocean', mn: 'Далай', kk: 'Мұхит' }, hint: { en: 'Deep', mn: 'Гүн', kk: 'Терең' } },
  { word: { en: 'Lake', mn: 'Нуур', kk: 'Көл' }, hint: { en: 'Calm', mn: 'Тайван', kk: 'Тыныш' } },
  { word: { en: 'Sand', mn: 'Элс', kk: 'Құм' }, hint: { en: 'Beach', mn: 'Эрэг', kk: 'Жағажай' } },
  { word: { en: 'Stone', mn: 'Чулуу', kk: 'Тас' }, hint: { en: 'Hard', mn: 'Хатуу', kk: 'Қатты' } },
  { word: { en: 'Earthquake', mn: 'Газар хөдлөлт', kk: 'Жер сілкінісі' }, hint: { en: 'Shake', mn: 'Доргих', kk: 'Сілкіну' } },

  // ── Household & objects ──────────────────────────────────
  { word: { en: 'Chair', mn: 'Сандал', kk: 'Орындық' }, hint: { en: 'Sit', mn: 'Суух', kk: 'Отыру' } },
  { word: { en: 'Table', mn: 'Ширээ', kk: 'Үстел' }, hint: { en: 'Dinner', mn: 'Оройн хоол', kk: 'Кешкі ас' } },
  { word: { en: 'Bed', mn: 'Ор', kk: 'Төсек' }, hint: { en: 'Sleep', mn: 'Унтах', kk: 'Ұйқы' } },
  { word: { en: 'Door', mn: 'Хаалга', kk: 'Есік' }, hint: { en: 'Open', mn: 'Нээх', kk: 'Ашу' } },
  { word: { en: 'Window', mn: 'Цонх', kk: 'Терезе' }, hint: { en: 'Glass', mn: 'Шил', kk: 'Шыны' } },
  { word: { en: 'Mirror', mn: 'Толь', kk: 'Айна' }, hint: { en: 'Reflection', mn: 'Тусгал', kk: 'Бейне' } },
  { word: { en: 'Clock', mn: 'Цаг', kk: 'Сағат' }, hint: { en: 'Time', mn: 'Хугацаа', kk: 'Уақыт' } },
  { word: { en: 'Lamp', mn: 'Чийдэн', kk: 'Шам' }, hint: { en: 'Light', mn: 'Гэрэл', kk: 'Жарық' } },
  { word: { en: 'Key', mn: 'Түлхүүр', kk: 'Кілт' }, hint: { en: 'Lock', mn: 'Цоож', kk: 'Құлып' } },
  { word: { en: 'Spoon', mn: 'Халбага', kk: 'Қасық' }, hint: { en: 'Soup', mn: 'Шөл', kk: 'Сорпа' } },
  { word: { en: 'Knife', mn: 'Хутга', kk: 'Пышақ' }, hint: { en: 'Cut', mn: 'Хэрчих', kk: 'Кесу' } },
  { word: { en: 'Fork', mn: 'Сэрээ', kk: 'Шанышқы' }, hint: { en: 'Eat', mn: 'Идэх', kk: 'Жеу' } },
  { word: { en: 'Cup', mn: 'Аяга', kk: 'Кесе' }, hint: { en: 'Tea', mn: 'Цай', kk: 'Шай' } },
  { word: { en: 'Plate', mn: 'Таваг', kk: 'Тәрелке' }, hint: { en: 'Food', mn: 'Хоол', kk: 'Тамақ' } },
  { word: { en: 'Bottle', mn: 'Шил', kk: 'Бөтелке' }, hint: { en: 'Water', mn: 'Ус', kk: 'Су' } },
  { word: { en: 'Pillow', mn: 'Дэр', kk: 'Жастық' }, hint: { en: 'Sleep', mn: 'Нойр', kk: 'Ұйқы' } },
  { word: { en: 'Blanket', mn: 'Хөнжил', kk: 'Көрпе' }, hint: { en: 'Warm', mn: 'Дулаан', kk: 'Жылы' } },
  { word: { en: 'Towel', mn: 'Алчуур', kk: 'Сүлгі' }, hint: { en: 'Dry', mn: 'Хатаах', kk: 'Кептіру' } },
  { word: { en: 'Soap', mn: 'Саван', kk: 'Сабын' }, hint: { en: 'Wash', mn: 'Угаах', kk: 'Жуу' } },
  { word: { en: 'Brush', mn: 'Сойз', kk: 'Қылшақ' }, hint: { en: 'Teeth', mn: 'Шүд', kk: 'Тіс' } },
  { word: { en: 'Umbrella', mn: 'Шүхэр', kk: 'Қолшатыр' }, hint: { en: 'Rain', mn: 'Бороо', kk: 'Жаңбыр' } },
  { word: { en: 'Candle', mn: 'Лаа', kk: 'Шырақ' }, hint: { en: 'Flame', mn: 'Дөл', kk: 'Жалын' } },
  { word: { en: 'Broom', mn: 'Шүүр', kk: 'Сыпырғы' }, hint: { en: 'Clean', mn: 'Цэвэрлэх', kk: 'Тазалау' } },
  { word: { en: 'Scissors', mn: 'Хайч', kk: 'Қайшы' }, hint: { en: 'Cut', mn: 'Тайрах', kk: 'Қию' } },
  { word: { en: 'Basket', mn: 'Сагс', kk: 'Себет' }, hint: { en: 'Carry', mn: 'Зөөх', kk: 'Тасу' } },
  { word: { en: 'Box', mn: 'Хайрцаг', kk: 'Қорап' }, hint: { en: 'Gift', mn: 'Бэлэг', kk: 'Сыйлық' } },
  { word: { en: 'Rope', mn: 'Олс', kk: 'Арқан' }, hint: { en: 'Tie', mn: 'Уях', kk: 'Байлау' } },
  { word: { en: 'Bucket', mn: 'Хувин', kk: 'Шелек' }, hint: { en: 'Water', mn: 'Ус', kk: 'Су' } },
  { word: { en: 'Needle', mn: 'Зүү', kk: 'Ине' }, hint: { en: 'Thread', mn: 'Утас', kk: 'Жіп' } },

  // ── Technology ───────────────────────────────────────────
  { word: { en: 'Phone', mn: 'Утас', kk: 'Телефон' }, hint: { en: 'Screen', mn: 'Дэлгэц', kk: 'Экран' } },
  { word: { en: 'Computer', mn: 'Компьютер', kk: 'Компьютер' }, hint: { en: 'Keyboard', mn: 'Гар', kk: 'Пернетақта' } },
  { word: { en: 'Television', mn: 'Зурагт', kk: 'Теледидар' }, hint: { en: 'Channel', mn: 'Суваг', kk: 'Арна' } },
  { word: { en: 'Camera', mn: 'Камер', kk: 'Камера' }, hint: { en: 'Photo', mn: 'Зураг', kk: 'Сурет' } },
  { word: { en: 'Robot', mn: 'Робот', kk: 'Робот' }, hint: { en: 'Machine', mn: 'Машин', kk: 'Машина' } },
  { word: { en: 'Internet', mn: 'Интернэт', kk: 'Интернет' }, hint: { en: 'Wifi', mn: 'Вайфай', kk: 'Wifi' } },
  { word: { en: 'Battery', mn: 'Батарей', kk: 'Батарея' }, hint: { en: 'Power', mn: 'Цэнэг', kk: 'Қуат' } },
  { word: { en: 'Headphones', mn: 'Чихэвч', kk: 'Құлаққап' }, hint: { en: 'Music', mn: 'Хөгжим', kk: 'Музыка' } },
  { word: { en: 'Printer', mn: 'Принтер', kk: 'Принтер' }, hint: { en: 'Paper', mn: 'Цаас', kk: 'Қағаз' } },
  { word: { en: 'Drone', mn: 'Дрон', kk: 'Дрон' }, hint: { en: 'Fly', mn: 'Нисэх', kk: 'Ұшу' } },
  { word: { en: 'Speaker', mn: 'Чанга яригч', kk: 'Динамик' }, hint: { en: 'Sound', mn: 'Чимээ', kk: 'Дыбыс' } },
  { word: { en: 'Charger', mn: 'Цэнэглэгч', kk: 'Зарядтағыш' }, hint: { en: 'Cable', mn: 'Утас', kk: 'Сым' } },
  { word: { en: 'Satellite', mn: 'Хиймэл дагуул', kk: 'Спутник' }, hint: { en: 'Orbit', mn: 'Тойрог зам', kk: 'Орбита' } },
  { word: { en: 'Microphone', mn: 'Микрофон', kk: 'Микрофон' }, hint: { en: 'Voice', mn: 'Дуу хоолой', kk: 'Дауыс' } },

  // ── Transport ────────────────────────────────────────────
  { word: { en: 'Car', mn: 'Машин', kk: 'Көлік' }, hint: { en: 'Road', mn: 'Зам', kk: 'Жол' } },
  { word: { en: 'Bus', mn: 'Автобус', kk: 'Автобус' }, hint: { en: 'Stop', mn: 'Буудал', kk: 'Аялдама' } },
  { word: { en: 'Train', mn: 'Галт тэрэг', kk: 'Пойыз' }, hint: { en: 'Rail', mn: 'Төмөр зам', kk: 'Темір жол' } },
  { word: { en: 'Airplane', mn: 'Онгоц', kk: 'Ұшақ' }, hint: { en: 'Sky', mn: 'Тэнгэр', kk: 'Аспан' } },
  { word: { en: 'Ship', mn: 'Хөлөг онгоц', kk: 'Кеме' }, hint: { en: 'Sea', mn: 'Тэнгис', kk: 'Теңіз' } },
  { word: { en: 'Boat', mn: 'Завь', kk: 'Қайық' }, hint: { en: 'River', mn: 'Гол', kk: 'Өзен' } },
  { word: { en: 'Bicycle', mn: 'Дугуй', kk: 'Велосипед' }, hint: { en: 'Two wheels', mn: 'Хоёр дугуй', kk: 'Екі дөңгелек' } },
  { word: { en: 'Motorcycle', mn: 'Мотоцикл', kk: 'Мотоцикл' }, hint: { en: 'Speed', mn: 'Хурд', kk: 'Жылдамдық' } },
  { word: { en: 'Helicopter', mn: 'Нисдэг тэрэг', kk: 'Тікұшақ' }, hint: { en: 'Blade', mn: 'Сэнс', kk: 'Қалақ' } },
  { word: { en: 'Rocket', mn: 'Пуужин', kk: 'Зымыран' }, hint: { en: 'Space', mn: 'Сансар', kk: 'Ғарыш' } },
  { word: { en: 'Truck', mn: 'Ачааны машин', kk: 'Жүк көлігі' }, hint: { en: 'Cargo', mn: 'Ачаа', kk: 'Жүк' } },
  { word: { en: 'Taxi', mn: 'Такси', kk: 'Такси' }, hint: { en: 'Fare', mn: 'Зардал', kk: 'Жол ақы' } },
  { word: { en: 'Submarine', mn: 'Шумбагч онгоц', kk: 'Сүңгуір қайық' }, hint: { en: 'Underwater', mn: 'Усан доорх', kk: 'Су асты' } },
  { word: { en: 'Tractor', mn: 'Трактор', kk: 'Трактор' }, hint: { en: 'Field', mn: 'Тариалан', kk: 'Егін' } },

  // ── Clothing ─────────────────────────────────────────────
  { word: { en: 'Shirt', mn: 'Цамц', kk: 'Жейде' }, hint: { en: 'Button', mn: 'Товч', kk: 'Түйме' } },
  { word: { en: 'Shoes', mn: 'Гутал', kk: 'Аяқкиім' }, hint: { en: 'Feet', mn: 'Хөл', kk: 'Аяқ' } },
  { word: { en: 'Hat', mn: 'Малгай', kk: 'Бас киім' }, hint: { en: 'Head', mn: 'Толгой', kk: 'Бас' } },
  { word: { en: 'Gloves', mn: 'Бээлий', kk: 'Қолғап' }, hint: { en: 'Hands', mn: 'Гар', kk: 'Қол' } },
  { word: { en: 'Scarf', mn: 'Ороолт', kk: 'Орамал' }, hint: { en: 'Neck', mn: 'Хүзүү', kk: 'Мойын' } },
  { word: { en: 'Socks', mn: 'Оймс', kk: 'Шұлық' }, hint: { en: 'Feet', mn: 'Хөл', kk: 'Аяқ' } },
  { word: { en: 'Jacket', mn: 'Хүрэм', kk: 'Күрте' }, hint: { en: 'Cold', mn: 'Хүйтэн', kk: 'Суық' } },
  { word: { en: 'Dress', mn: 'Даашинз', kk: 'Көйлек' }, hint: { en: 'Elegant', mn: 'Гоёмсог', kk: 'Сәнді' } },
  { word: { en: 'Belt', mn: 'Бүс', kk: 'Белбеу' }, hint: { en: 'Waist', mn: 'Бэлхүүс', kk: 'Бел' } },
  { word: { en: 'Ring', mn: 'Бөгж', kk: 'Сақина' }, hint: { en: 'Finger', mn: 'Хуруу', kk: 'Саусақ' } },
  { word: { en: 'Watch', mn: 'Бугуйн цаг', kk: 'Қол сағат' }, hint: { en: 'Time', mn: 'Цаг', kk: 'Уақыт' } },
  { word: { en: 'Glasses', mn: 'Нүдний шил', kk: 'Көзілдірік' }, hint: { en: 'Eyes', mn: 'Нүд', kk: 'Көз' } },
  { word: { en: 'Crown', mn: 'Титэм', kk: 'Тәж' }, hint: { en: 'King', mn: 'Хаан', kk: 'Патша' } },
  { word: { en: 'Boots', mn: 'Гутал', kk: 'Етік' }, hint: { en: 'Snow', mn: 'Цас', kk: 'Қар' } },

  // ── Music & instruments ──────────────────────────────────
  { word: { en: 'Guitar', mn: 'Гитар', kk: 'Гитара' }, hint: { en: 'Concert', mn: 'Тоглолт', kk: 'Концерт' } },
  { word: { en: 'Piano', mn: 'Төгөлдөр хуур', kk: 'Фортепиано' }, hint: { en: 'Keys', mn: 'Товчлуур', kk: 'Перне' } },
  { word: { en: 'Drum', mn: 'Бөмбөр', kk: 'Барабан' }, hint: { en: 'Beat', mn: 'Цохилт', kk: 'Соққы' } },
  { word: { en: 'Violin', mn: 'Хийл', kk: 'Скрипка' }, hint: { en: 'String', mn: 'Утас', kk: 'Ішек' } },
  { word: { en: 'Flute', mn: 'Лимбэ', kk: 'Сыбызғы' }, hint: { en: 'Breath', mn: 'Амьсгал', kk: 'Дем' } },
  { word: { en: 'Trumpet', mn: 'Бүрээ', kk: 'Керней' }, hint: { en: 'Brass', mn: 'Гууль', kk: 'Жез' } },
  { word: { en: 'Saxophone', mn: 'Саксофон', kk: 'Саксофон' }, hint: { en: 'Jazz', mn: 'Жаз', kk: 'Джаз' } },
  { word: { en: 'Microphone song', mn: 'Караоке', kk: 'Караоке' }, hint: { en: 'Sing', mn: 'Дуулах', kk: 'Ән айту' } },

  // ── Body ─────────────────────────────────────────────────
  { word: { en: 'Heart', mn: 'Зүрх', kk: 'Жүрек' }, hint: { en: 'Beat', mn: 'Цохилт', kk: 'Соғу' } },
  { word: { en: 'Eye', mn: 'Нүд', kk: 'Көз' }, hint: { en: 'See', mn: 'Харах', kk: 'Көру' } },
  { word: { en: 'Hand', mn: 'Гар', kk: 'Қол' }, hint: { en: 'Five', mn: 'Тав', kk: 'Бес' } },
  { word: { en: 'Tooth', mn: 'Шүд', kk: 'Тіс' }, hint: { en: 'Bite', mn: 'Хазах', kk: 'Тістеу' } },
  { word: { en: 'Hair', mn: 'Үс', kk: 'Шаш' }, hint: { en: 'Comb', mn: 'Сам', kk: 'Тарақ' } },
  { word: { en: 'Brain', mn: 'Тархи', kk: 'Ми' }, hint: { en: 'Think', mn: 'Бодох', kk: 'Ойлау' } },
  { word: { en: 'Bone', mn: 'Яс', kk: 'Сүйек' }, hint: { en: 'Skeleton', mn: 'Араг яс', kk: 'Қаңқа' } },
  { word: { en: 'Tongue', mn: 'Хэл', kk: 'Тіл' }, hint: { en: 'Taste', mn: 'Амт', kk: 'Дәм' } },

  // ── Concepts, events, misc ───────────────────────────────
  { word: { en: 'Wedding', mn: 'Хурим', kk: 'Той' }, hint: { en: 'Love', mn: 'Хайр', kk: 'Махаббат' } },
  { word: { en: 'Birthday', mn: 'Төрсөн өдөр', kk: 'Туған күн' }, hint: { en: 'Candle', mn: 'Лаа', kk: 'Шырақ' } },
  { word: { en: 'Holiday', mn: 'Баяр', kk: 'Мереке' }, hint: { en: 'Rest', mn: 'Амралт', kk: 'Демалыс' } },
  { word: { en: 'Money', mn: 'Мөнгө', kk: 'Ақша' }, hint: { en: 'Wallet', mn: 'Хэтэвч', kk: 'Әмиян' } },
  { word: { en: 'Gold', mn: 'Алт', kk: 'Алтын' }, hint: { en: 'Treasure', mn: 'Эрдэнэ', kk: 'Қазына' } },
  { word: { en: 'Map', mn: 'Газрын зураг', kk: 'Карта' }, hint: { en: 'Travel', mn: 'Аялал', kk: 'Саяхат' } },
  { word: { en: 'Ticket', mn: 'Тасалбар', kk: 'Билет' }, hint: { en: 'Entry', mn: 'Орох', kk: 'Кіру' } },
  { word: { en: 'Letter', mn: 'Захидал', kk: 'Хат' }, hint: { en: 'Post', mn: 'Шуудан', kk: 'Пошта' } },
  { word: { en: 'Photo', mn: 'Гэрэл зураг', kk: 'Сурет' }, hint: { en: 'Memory', mn: 'Дурсамж', kk: 'Естелік' } },
  { word: { en: 'Dream', mn: 'Зүүд', kk: 'Түс' }, hint: { en: 'Sleep', mn: 'Нойр', kk: 'Ұйқы' } },
  { word: { en: 'Shadow', mn: 'Сүүдэр', kk: 'Көлеңке' }, hint: { en: 'Light', mn: 'Гэрэл', kk: 'Жарық' } },
  { word: { en: 'Ghost', mn: 'Сүнс', kk: 'Елес' }, hint: { en: 'Fear', mn: 'Айдас', kk: 'Қорқыныш' } },
  { word: { en: 'Dragon', mn: 'Луу', kk: 'Айдаһар' }, hint: { en: 'Legend', mn: 'Домог', kk: 'Аңыз' } },
  { word: { en: 'Treasure', mn: 'Эрдэнэс', kk: 'Қазына' }, hint: { en: 'Pirate', mn: 'Далайн дээрэм', kk: 'Қарақшы' } },
  { word: { en: 'Balloon', mn: 'Бөмбөлөг', kk: 'Шар' }, hint: { en: 'Air', mn: 'Агаар', kk: 'Ауа' } },
  { word: { en: 'Kite', mn: 'Цаасан шувуу', kk: 'Батпырауық' }, hint: { en: 'Wind', mn: 'Салхи', kk: 'Жел' } },
  { word: { en: 'Toy', mn: 'Тоглоом', kk: 'Ойыншық' }, hint: { en: 'Child', mn: 'Хүүхэд', kk: 'Бала' } },
  { word: { en: 'Ball', mn: 'Бөмбөг', kk: 'Доп' }, hint: { en: 'Round', mn: 'Дугуй', kk: 'Дөңгелек' } },
  { word: { en: 'Flag', mn: 'Туг', kk: 'Ту' }, hint: { en: 'Country', mn: 'Улс', kk: 'Ел' } },
  { word: { en: 'Coin', mn: 'Зоос', kk: 'Тиын' }, hint: { en: 'Metal', mn: 'Төмөр', kk: 'Метал' } },
  { word: { en: 'Diamond', mn: 'Очир алмаз', kk: 'Гауһар' }, hint: { en: 'Shine', mn: 'Гялбаа', kk: 'Жарқырау' } },
  { word: { en: 'Compass', mn: 'Луужин', kk: 'Компас' }, hint: { en: 'North', mn: 'Хойд', kk: 'Солтүстік' } },
  { word: { en: 'Telescope', mn: 'Дуран', kk: 'Телескоп' }, hint: { en: 'Star', mn: 'Од', kk: 'Жұлдыз' } },
  { word: { en: 'Anchor', mn: 'Зангуу', kk: 'Зәкір' }, hint: { en: 'Ship', mn: 'Онгоц', kk: 'Кеме' } },
  { word: { en: 'Hammer', mn: 'Алх', kk: 'Балға' }, hint: { en: 'Nail', mn: 'Хадаас', kk: 'Шеге' } },
  { word: { en: 'Saw', mn: 'Хөрөө', kk: 'Ара' }, hint: { en: 'Wood', mn: 'Мод', kk: 'Ағаш' } },
  { word: { en: 'Ladder', mn: 'Шат', kk: 'Саты' }, hint: { en: 'Climb', mn: 'Авирах', kk: 'Өрмелеу' } },
  { word: { en: 'Gun', mn: 'Буу', kk: 'Мылтық' }, hint: { en: 'Bullet', mn: 'Сум', kk: 'Оқ' } },
  { word: { en: 'Sword', mn: 'Илд', kk: 'Қылыш' }, hint: { en: 'Knight', mn: 'Баатар', kk: 'Сарбаз' } },
  { word: { en: 'Shield', mn: 'Бамбай', kk: 'Қалқан' }, hint: { en: 'Defend', mn: 'Хамгаалах', kk: 'Қорғау' } },
  { word: { en: 'Bow', mn: 'Нум', kk: 'Садақ' }, hint: { en: 'Arrow', mn: 'Сум', kk: 'Жебе' } },
  { word: { en: 'Drum song', mn: 'Морин хуур', kk: 'Қобыз' }, hint: { en: 'Tradition', mn: 'Уламжлал', kk: 'Дәстүр' } },
  { word: { en: 'Yurt', mn: 'Гэр', kk: 'Киіз үй' }, hint: { en: 'Nomad', mn: 'Нүүдэлчин', kk: 'Көшпенді' } },
  { word: { en: 'Saddle', mn: 'Эмээл', kk: 'Ер' }, hint: { en: 'Horse', mn: 'Морь', kk: 'Жылқы' } },
  { word: { en: 'Whip', mn: 'Ташуур', kk: 'Қамшы' }, hint: { en: 'Ride', mn: 'Унах', kk: 'Міну' } },
  { word: { en: 'Eagle hunter', mn: 'Бүргэдчин', kk: 'Бүркітші' }, hint: { en: 'Mountain', mn: 'Уул', kk: 'Тау' } },
  { word: { en: 'Fireplace', mn: 'Зуух', kk: 'Пеш' }, hint: { en: 'Warm', mn: 'Дулаан', kk: 'Жылу' } },
  { word: { en: 'Mirror lake', mn: 'Рашаан', kk: 'Бұлақ' }, hint: { en: 'Spring water', mn: 'Булаг', kk: 'Қайнар' } },
  { word: { en: 'Snowman', mn: 'Цасан хүн', kk: 'Аққала' }, hint: { en: 'Winter', mn: 'Өвөл', kk: 'Қыс' } },
  { word: { en: 'Volcano ash', mn: 'Үнс', kk: 'Күл' }, hint: { en: 'Fire', mn: 'Гал', kk: 'От' } },
  { word: { en: 'Rainforest', mn: 'Ширэнгэн ой', kk: 'Джунгли' }, hint: { en: 'Wet', mn: 'Чийглэг', kk: 'Ылғал' } },
  { word: { en: 'Glacier', mn: 'Мөсөн гол', kk: 'Мұздық' }, hint: { en: 'Frozen', mn: 'Хөлдүү', kk: 'Қатқан' } },
  { word: { en: 'Cliff', mn: 'Хад', kk: 'Жартас' }, hint: { en: 'Edge', mn: 'Ирмэг', kk: 'Шеті' } },
  { word: { en: 'Meteor', mn: 'Солир', kk: 'Метеор' }, hint: { en: 'Sky', mn: 'Тэнгэр', kk: 'Аспан' } },
  { word: { en: 'Comet', mn: 'Сүүлт од', kk: 'Құйрықты жұлдыз' }, hint: { en: 'Tail', mn: 'Сүүл', kk: 'Құйрық' } },
  { word: { en: 'Planet', mn: 'Гараг', kk: 'Планета' }, hint: { en: 'Orbit', mn: 'Тойрог', kk: 'Орбита' } },
  { word: { en: 'Galaxy', mn: 'Галактик', kk: 'Галактика' }, hint: { en: 'Stars', mn: 'Одод', kk: 'Жұлдыздар' } },
  { word: { en: 'Lightning', mn: 'Цахилгаан', kk: 'Найзағай' }, hint: { en: 'Flash', mn: 'Гялбаа', kk: 'Жарқыл' } },
  { word: { en: 'Tornado', mn: 'Хар салхи', kk: 'Дауыл' }, hint: { en: 'Spin', mn: 'Эргэх', kk: 'Айналу' } },
  { word: { en: 'Avalanche', mn: 'Нуранги', kk: 'Көшкін' }, hint: { en: 'Snow', mn: 'Цас', kk: 'Қар' } },

  // ── More food & objects to round out ─────────────────────
  { word: { en: 'Yogurt', mn: 'Тараг', kk: 'Айран' }, hint: { en: 'Sour', mn: 'Исгэлэн', kk: 'Қышқыл' } },
  { word: { en: 'Butter', mn: 'Цөцгийн тос', kk: 'Сары май' }, hint: { en: 'Bread', mn: 'Талх', kk: 'Нан' } },
  { word: { en: 'Jam', mn: 'Чанамал', kk: 'Тосап' }, hint: { en: 'Berry', mn: 'Жимс', kk: 'Жидек' } },
  { word: { en: 'Pepper', mn: 'Чинжүү', kk: 'Бұрыш' }, hint: { en: 'Spicy', mn: 'Халуун ногоо', kk: 'Ащы' } },
  { word: { en: 'Cookie', mn: 'Жигнэмэг', kk: 'Печенье' }, hint: { en: 'Sweet', mn: 'Чихэрлэг', kk: 'Тәтті' } },
  { word: { en: 'Sandwich', mn: 'Сэндвич', kk: 'Бутерброд' }, hint: { en: 'Lunch', mn: 'Өдрийн хоол', kk: 'Түскі ас' } },
  { word: { en: 'Corn', mn: 'Эрдэнэ шиш', kk: 'Жүгері' }, hint: { en: 'Yellow', mn: 'Шар', kk: 'Сары' } },
  { word: { en: 'Pumpkin', mn: 'Хулуу', kk: 'Асқабақ' }, hint: { en: 'Autumn', mn: 'Намар', kk: 'Күз' } },
  { word: { en: 'Mango', mn: 'Манго', kk: 'Манго' }, hint: { en: 'Tropical', mn: 'Халуун орны', kk: 'Тропик' } },
  { word: { en: 'Coconut', mn: 'Кокос', kk: 'Кокос' }, hint: { en: 'Palm', mn: 'Далдуу', kk: 'Пальма' } },
  { word: { en: 'Pineapple', mn: 'Хан боргоцой', kk: 'Ананас' }, hint: { en: 'Tropical', mn: 'Халуун орны', kk: 'Тропик' } },
  { word: { en: 'Cherry', mn: 'Интоор', kk: 'Шие' }, hint: { en: 'Red', mn: 'Улаан', kk: 'Қызыл' } },
  { word: { en: 'Peach', mn: 'Тоор', kk: 'Шабдалы' }, hint: { en: 'Soft', mn: 'Зөөлөн', kk: 'Жұмсақ' } },
  { word: { en: 'Pear', mn: 'Лийр', kk: 'Алмұрт' }, hint: { en: 'Fruit', mn: 'Жимс', kk: 'Жеміс' } },
  { word: { en: 'Cucumber', mn: 'Өргөст хэмх', kk: 'Қияр' }, hint: { en: 'Salad', mn: 'Салат', kk: 'Салат' } },
  { word: { en: 'Cabbage', mn: 'Байцаа', kk: 'Қырыққабат' }, hint: { en: 'Green', mn: 'Ногоон', kk: 'Жасыл' } },

  // ── Misc everyday ────────────────────────────────────────
  { word: { en: 'Pencil', mn: 'Харандаа', kk: 'Қарындаш' }, hint: { en: 'Draw', mn: 'Зурах', kk: 'Сызу' } },
  { word: { en: 'Pen', mn: 'Бал', kk: 'Қалам' }, hint: { en: 'Write', mn: 'Бичих', kk: 'Жазу' } },
  { word: { en: 'Paper', mn: 'Цаас', kk: 'Қағаз' }, hint: { en: 'White', mn: 'Цагаан', kk: 'Ақ' } },
  { word: { en: 'Book', mn: 'Ном', kk: 'Кітап' }, hint: { en: 'Library', mn: 'Номын сан', kk: 'Кітапхана' } },
  { word: { en: 'Newspaper', mn: 'Сонин', kk: 'Газет' }, hint: { en: 'News', mn: 'Мэдээ', kk: 'Жаңалық' } },
  { word: { en: 'Calendar', mn: 'Хуанли', kk: 'Күнтізбе' }, hint: { en: 'Date', mn: 'Огноо', kk: 'Күн' } },
  { word: { en: 'Wallet', mn: 'Хэтэвч', kk: 'Әмиян' }, hint: { en: 'Money', mn: 'Мөнгө', kk: 'Ақша' } },
  { word: { en: 'Bag', mn: 'Цүнх', kk: 'Сөмке' }, hint: { en: 'Carry', mn: 'Зөөх', kk: 'Тасу' } },
  { word: { en: 'Suitcase', mn: 'Чемодан', kk: 'Чемодан' }, hint: { en: 'Travel', mn: 'Аялал', kk: 'Саяхат' } },
  { word: { en: 'Toothbrush', mn: 'Шүдний сойз', kk: 'Тіс щеткасы' }, hint: { en: 'Clean', mn: 'Цэвэрлэх', kk: 'Тазалау' } },
  { word: { en: 'Comb', mn: 'Сам', kk: 'Тарақ' }, hint: { en: 'Hair', mn: 'Үс', kk: 'Шаш' } },
  { word: { en: 'Fan', mn: 'Сэнс', kk: 'Желдеткіш' }, hint: { en: 'Cool', mn: 'Сэрүүн', kk: 'Салқын' } },
  { word: { en: 'Heater', mn: 'Халаагуур', kk: 'Жылытқыш' }, hint: { en: 'Warm', mn: 'Дулаан', kk: 'Жылы' } },
  { word: { en: 'Fridge', mn: 'Хөргөгч', kk: 'Тоңазытқыш' }, hint: { en: 'Cold', mn: 'Хүйтэн', kk: 'Суық' } },
  { word: { en: 'Oven', mn: 'Зуух', kk: 'Пеш' }, hint: { en: 'Bake', mn: 'Жигнэх', kk: 'Пісіру' } },
  { word: { en: 'Kettle', mn: 'Данх', kk: 'Шәйнек' }, hint: { en: 'Boil', mn: 'Буцлах', kk: 'Қайнау' } },
]

const HARD_HINTS = [
  {
    end: 46,
    hints: [
      { en: 'Living thing', mn: 'Амьд зүйл', kk: 'Тірі нәрсе' },
      { en: 'Movement', mn: 'Хөдөлгөөн', kk: 'Қозғалыс' },
      { en: 'Habitat', mn: 'Орчин', kk: 'Мекен' },
      { en: 'Wild side', mn: 'Зэрлэг тал', kk: 'Жабайы жақ' },
    ],
  },
  {
    end: 81,
    hints: [
      { en: 'Taste', mn: 'Амт', kk: 'Дәм' },
      { en: 'Meal time', mn: 'Хоолны цаг', kk: 'Ас уақыты' },
      { en: 'Kitchen', mn: 'Гал тогоо', kk: 'Ас үй' },
      { en: 'Texture', mn: 'Бүтэц', kk: 'Құрылым' },
    ],
  },
  {
    end: 109,
    hints: [
      { en: 'Somewhere', mn: 'Хаа нэг газар', kk: 'Бір жер' },
      { en: 'Visitors', mn: 'Зочид', kk: 'Келушілер' },
      { en: 'Map point', mn: 'Газрын цэг', kk: 'Картадағы нүкте' },
      { en: 'Public space', mn: 'Олон нийтийн орон зай', kk: 'Қоғамдық орын' },
    ],
  },
  {
    end: 133,
    hints: [
      { en: 'Work', mn: 'Ажил', kk: 'Жұмыс' },
      { en: 'Skill', mn: 'Ур чадвар', kk: 'Дағды' },
      { en: 'Responsibility', mn: 'Хариуцлага', kk: 'Жауапкершілік' },
      { en: 'Uniform maybe', mn: 'Дүрэмт хувцас байж магадгүй', kk: 'Форма болуы мүмкін' },
    ],
  },
  {
    end: 148,
    hints: [
      { en: 'Rules', mn: 'Дүрэм', kk: 'Ереже' },
      { en: 'Competition', mn: 'Өрсөлдөөн', kk: 'Жарыс' },
      { en: 'Score', mn: 'Оноо', kk: 'Ұпай' },
      { en: 'Practice', mn: 'Дасгал', kk: 'Жаттығу' },
    ],
  },
  {
    end: 171,
    hints: [
      { en: 'Outside', mn: 'Гадаа', kk: 'Сыртта' },
      { en: 'Season', mn: 'Улирал', kk: 'Маусым' },
      { en: 'Sky or ground', mn: 'Тэнгэр эсвэл газар', kk: 'Аспан не жер' },
      { en: 'Natural force', mn: 'Байгалийн хүч', kk: 'Табиғи күш' },
    ],
  },
  {
    end: 200,
    hints: [
      { en: 'At home', mn: 'Гэрт', kk: 'Үйде' },
      { en: 'Everyday use', mn: 'Өдөр тутмын хэрэглээ', kk: 'Күнделікті қолдану' },
      { en: 'Touch or hold', mn: 'Барьж эсвэл хүрнэ', kk: 'Ұстау не тию' },
      { en: 'Useful object', mn: 'Хэрэгтэй зүйл', kk: 'Пайдалы зат' },
    ],
  },
  {
    end: 214,
    hints: [
      { en: 'Device', mn: 'Төхөөрөмж', kk: 'Құрылғы' },
      { en: 'Signal', mn: 'Дохио', kk: 'Сигнал' },
      { en: 'Screen or sound', mn: 'Дэлгэц эсвэл дуу', kk: 'Экран не дыбыс' },
      { en: 'Modern tool', mn: 'Орчин үеийн хэрэгсэл', kk: 'Заманауи құрал' },
    ],
  },
  {
    end: 228,
    hints: [
      { en: 'Travel', mn: 'Явах', kk: 'Жүру' },
      { en: 'Route', mn: 'Чиглэл', kk: 'Бағыт' },
      { en: 'Speed', mn: 'Хурд', kk: 'Жылдамдық' },
      { en: 'From here to there', mn: 'Эндээс тийш', kk: 'Осы жерден ана жаққа' },
    ],
  },
  {
    end: 242,
    hints: [
      { en: 'Wearable', mn: 'Өмсдөг зүйл', kk: 'Киетін зат' },
      { en: 'Style', mn: 'Хэв маяг', kk: 'Стиль' },
      { en: 'Weather choice', mn: 'Цаг агаараас хамаарна', kk: 'Ауа райына байланысты' },
      { en: 'On the body', mn: 'Биед', kk: 'Денеде' },
    ],
  },
  {
    end: 250,
    hints: [
      { en: 'Sound', mn: 'Дуу чимээ', kk: 'Дыбыс' },
      { en: 'Performance', mn: 'Тоглолт', kk: 'Орындау' },
      { en: 'Rhythm', mn: 'Хэмнэл', kk: 'Ырғақ' },
      { en: 'Practice needed', mn: 'Дасгал хэрэгтэй', kk: 'Жаттығу керек' },
    ],
  },
  {
    end: 258,
    hints: [
      { en: 'Part of you', mn: 'Чиний нэг хэсэг', kk: 'Сенің бір бөлігің' },
      { en: 'Body signal', mn: 'Биеийн дохио', kk: 'Дене белгісі' },
      { en: 'Function', mn: 'Үүрэг', kk: 'Қызмет' },
      { en: 'Sensitive', mn: 'Мэдрэмтгий', kk: 'Сезімтал' },
    ],
  },
  {
    end: 308,
    hints: [
      { en: 'Idea', mn: 'Санаа', kk: 'Ой' },
      { en: 'Memory or story', mn: 'Дурсамж эсвэл түүх', kk: 'Естелік не оқиға' },
      { en: 'Symbol', mn: 'Бэлгэдэл', kk: 'Белгі' },
      { en: 'Not always visible', mn: 'Дандаа харагдахгүй', kk: 'Әрдайым көрінбейді' },
    ],
  },
  {
    end: 324,
    hints: [
      { en: 'Taste', mn: 'Амт', kk: 'Дәм' },
      { en: 'Meal time', mn: 'Хоолны цаг', kk: 'Ас уақыты' },
      { en: 'Kitchen', mn: 'Гал тогоо', kk: 'Ас үй' },
      { en: 'Fresh or stored', mn: 'Шинэ эсвэл хадгалсан', kk: 'Жаңа не сақталған' },
    ],
  },
  {
    end: 340,
    hints: [
      { en: 'Everyday use', mn: 'Өдөр тутмын хэрэглээ', kk: 'Күнделікті қолдану' },
      { en: 'Small detail', mn: 'Жижиг зүйл', kk: 'Ұсақ нәрсе' },
      { en: 'Routine', mn: 'Дадал', kk: 'Әдет' },
      { en: 'Useful object', mn: 'Хэрэгтэй зүйл', kk: 'Пайдалы зат' },
    ],
  },
]

function hardHintFor(index) {
  const category = HARD_HINTS.find((c) => index < c.end)
  if (!category) return RAW[index].hint
  return category.hints[index % category.hints.length]
}

// Remove any accidental duplicate words (keyed by the English word).
const seen = new Set()
export const WORDS = RAW.map((w, index) => ({
  ...w,
  hint: hardHintFor(index),
})).filter((w) => {
  const key = w.word.en.trim().toLowerCase()
  if (seen.has(key)) return false
  seen.add(key)
  return true
})

// Shuffle-bag: hand out every word once before any repeats.
let bag = []
function refillBag() {
  bag = WORDS.map((_, i) => i)
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[bag[i], bag[j]] = [bag[j], bag[i]]
  }
}
export function nextWordIndex() {
  if (bag.length === 0) refillBag()
  return bag.pop()
}
